name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Poetry and project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Run linting with Poe
      run: poetry run poe lint

    - name: Run formatting check with Poe
      run: poetry run poe format
